### ISSUE TITLE
$order = new WechatOrder($orderData);  这个不能用

### ISSUE THREAD

**Issue by arieslee** [max-wen/yii2-easy-wechat#14]
说找不到WechatOrder.
是不是要自己写这个类呀？

**Comment by imaxwen** [comment]
@arieslee  命名空间引入了？

**Comment by arieslee** [comment]
@max-wen 需要引入这个“maxwen\easywechat” 还是"maxwen\easywechat\wechat"?

**Comment by imaxwen** [comment]
use **\**\WechatOrder

建议先了解一下PHP命名空间的使用
