### ISSUE TITLE
Undefined property: maxwen\easywechat\Wechat::$app

### ISSUE THREAD

**Issue by denghp** [max-wen/yii2-easy-wechat#3]

**Comment by imaxwen** [comment]
@denghp   能说的详细点吗？ 在何种情况下报错的？

**Comment by denghp** [comment]
php-7.0.3
yii2-2.0.10
直接调用 Yii::$app->wechat 就报这个问题

**Comment by zieglar** [comment]
同样出现了这个错误
确切的说是使用 Yii::$app->wechat->server 的时候就报错了
updated: 是我理解错误，appid 等配置直接配在 components 下了，希望 readme 能再清晰一点，现在有点误导人。

**Comment by 19z** [comment]
根据 https://github.com/max-wen/yii2-easy-wechat/blob/master/Wechat.php#L118 ，Application实例化所需要的config配置，要写在 Yii::$app->params['WECHAT'], 即 app/config/params.php  配置文件WECHAT 项中。
